website/views.py
from flask import Flask, Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from sqlalchemy.util.langhelpers import has_compiled_ext
from .models import Note
from . import db
import pickle
import json
#import pandas as pd
import requests
import logging

views = Blueprint('views', __name__)
#app = Blueprint('app', __name__)

#app = Flask(__name__)

# Configuração do logging
logging.basicConfig(level=logging.DEBUG)
"""
#Rota inicial 
@views.route('/')
def inicio():
    user = {'is_authenticated': False}  # Definindo um usuário fictício como não autenticado
    return render_template('index.html')
  

@views.route('/')
def inicio():
# Verifica se o usuário está autenticado de acordo com a lógica do Flask-Login
    return render_template('index.html')
"""

"""
# Carregue a lista de filmes uma vez ao iniciar o aplicativo
with open('models/filmes_dataframe.pkl', 'rb') as file:
    filmesData = pickle.load(file)

with open('models/filmes_df.pkl', 'rb') as file:
    filmesFilter = pickle.load(file)

# Carregar o modelo em um novo código
with open('models/modelo.pkl', 'rb') as file:
    similarity = pickle.load(file)
"""
# Não saberei explicar em detalhes, mas, em resumo, usa uma API que busca a logo dos filmes
def fetch_poster(movie_id):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US"
    try:
        data = requests.get(url)
        data = data.json()
        poster_path = data['poster_path']
        full_path = f"https://image.tmdb.org/t/p/w500/{poster_path}"
        return full_path
    except requests.exceptions.RequestException as e:
        logging.error(f"Erro ao fazer requisição à API: {e}")
        return None

def recommend(movie):
    logging.debug("Entrou na função recommend.")
    index = filmesData[filmesData['title'] == movie].index
    if len(index) > 0:
        index = index[0]
        distances = sorted(enumerate(similarity[index]),
                        reverse=True,
                        key=lambda x: x[1])
        recommended_movie_names = []
        recommended_movie_posters = []
        for i in distances[0:10]:
        # buscar o cartaz do filme 
            movie_id = filmesData.iloc[i[0]].movie_id
            recommended_movie_posters.append(fetch_poster(movie_id))
            recommended_movie_names.append(filmesData.iloc[i[0]].title)

        return recommended_movie_names, recommended_movie_posters
    else:
        return None, None

@views.route("/home", methods=["GET", "POST"])
@login_required
def index():
    logging.debug("Entrou na rota index.")

    generos = ['Action', 'Romance', 'Fantasy']
    nota_minima = 5
    ano_lancamento = 2017
    user_authenticated = current_user.is_authenticated  # Adicione esta linha
    
    if request.method == "POST":
        if "genres" in request.form:
            generos = request.form.getlist("genres")
        else:
            generos = ['Action', 'Romance', 'Fantasy']
        if "ratings" in request.form:
            nota_minima = int(request.form["ratings"])
        else:
            nota_minima = 5
        if "year" in request.form:
            ano_lancamento = int(request.form["year"])
        else:
            ano_lancamento = 2017

    if generos or nota_minima or ano_lancamento:
        filmes_selecionados = filmesFilter[
            (filmesFilter['genres'].apply(lambda x: all(genero in x for genero in generos))) if generos else True
            & (filmesFilter['vote_average'] >= nota_minima) if nota_minima else True
            & (filmesFilter['release_date'].apply(lambda x: int(x[:4]) <= ano_lancamento)) if ano_lancamento else True]

        print("Filmes selecionados:", filmes_selecionados)  # Adicione esta linha

    if not filmes_selecionados.empty:
        nome_do_filme = filmes_selecionados['title'].values[0]
    else:
        nome_do_filme = "Nenhum filme foi selecionado"
    
    selected_movie = nome_do_filme
    recommended_movie_names, recommended_movie_posters = recommend(selected_movie)

    # Passa os dados para o template
    movie_list = filmesData['title'].values
    # Verifica se o usuário está autenticado antes de passá-lo para o template
    user_authenticated = current_user.is_authenticated
    return render_template("home.html",
                        movie_list=movie_list,
                        selected_movie=selected_movie,
                        recommended_movie_names=recommended_movie_names,
                        recommended_movie_posters=recommended_movie_posters,
                        generos=generos,
                        ano_lancamento=ano_lancamento,
                        nota_minima=nota_minima,user_authenticated=user_authenticated,
                           user=current_user)  # Adicione esta linha)


# Adicionar Notas na Guia.
@views.route('/index', methods=['GET', 'POST'])
@login_required
def home():
    logging.debug("Entrou na rota home.")
    if request.method == 'POST':
        note = request.form.get('note')  # Obtém a nota do HTML
        logging.debug(f"Note to be added: {note}")
        
        if len(note) < 5:
            logging.warning("Nota muito curta.")
            flash('Nota muito curta!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)  # fornece o esquema para a nota
            db.session.add(new_note)  # adiciona a nota ao banco de dados
            db.session.commit()
            logging.debug("Nota adicionada com sucesso.")
            flash('Nota adicionada!', category='success')

    return render_template("home.html", user=current_user)


# Deletar notas da guia.
# Deletar notas da guia.
@views.route('/delete-note', methods=['POST'])
def delete_note():
    logging.debug("Entrou na rota delete-note.")
    try:
        note = json.loads(request.data)  # esta função espera um JSON do arquivo INDEX.js
        noteId = note['noteId']
        logging.debug(f"Tentando deletar nota com ID: {noteId}")
        note = Note.query.get(noteId)
        
        if note:
            if note.user_id == current_user.id:
                db.session.delete(note)
                db.session.commit()
                logging.debug("Nota deletada com sucesso.")
                flash('Nota deletada com sucesso!', category='success')
                return jsonify({"status": "success"})
            else:
                logging.warning("Usuário não autorizado a excluir esta nota.")
                return jsonify({"status": "unauthorized"})
        else:
            logging.warning("Nota não encontrada.")
            return jsonify({"status": "not_found"})
    except Exception as e:
        logging.error(f"Erro ao deletar nota: {e}")
        return jsonify({"status": "error"})

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

<!-- Adicione os links para os arquivos CSS do Swiper -->
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

    <!--
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='carrossel.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='header.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='topicos.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='banner.css') }}">
-->
    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.20.0/font/bootstrap-icons.css">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
<link rel="stylesheet" href="{{url_for('static', filename='login.css') }}">

<link rel="stylesheet" href="{{url_for('static', filename='style3.css') }}">

    <title>{% block title %}Home{% endblock %}</title>

    <style>
  body {
    background-image: url("{{ url_for('static', filename='img/back.jpg') }}");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    height: auto;
    max-width: auto;
    /* Outros estilos... */
  }
    </style>

  <style>
      @keyframes entrada {
           from {
               opacity: 0;
               transform: translateY(-20px);
           }
           to {
               opacity: 1;
               transform: translateY(0);
           }
       }

       h2 {
           animation: entrada 6s ease forwards;
           transition: transform 0.3s, color 0.3s;
       }

       h2:hover {
           transform: scale(1.1);
           color: #f50016; /* Cor quando o mouse está sobre o elemento */
       }

  </style>
  </head>
  <body>
<!--Codigo menu-->
<header>
  <nav class="nav-bar">
    <a href="/">
        <div class="logo">
            <img src="{{ url_for('static', filename='img/Cinemix.png') }}" alt="Logo Cinemix Movies" class="logo">
        </div>
    </a>
   <!-- <div class="nav-list">-->
    <div class="nav-list">
      <ul class="menu">
    {% if user.is_authenticated %}
        <li class="nav-item"><a id="home" href="/" class="nav-link">Início</a></li>
        <li class="nav-item"><a id="home" href="/home" class="nav-link">Guia</a></li>
        <li class="nav-item"><a id="home" href="/" class="nav-link">Sobre</a></li>
    <div class="logout-button">
    <a href="/logout " class="logout-link">Sair</a>
      </div>
        {% else %}
        <li class="nav-item"><a id="home" href="/" class="nav-link">Início</a></li>
        <li class="nav-item"><a id="signUp" href="/sign-up" class="nav-link">Cadastro</a></li>
      
      <li class="nav-item"><a id="home" href="/" class="nav-link">Sobre</a></li>
  <div class="login-button">
    <a href="/login" class="login-link">Entrar</a>
      </div>
    {% endif %}
  </ul>
  </div>
    <div class="mobile-menu-icon">
      <button onclick="menuShow()"><img class="icon" src="{{ url_for('static', filename='menu.svg') }}" alt=""></button>
    </div>
  </nav>
  <div class="mobile-menu">
    <ul class="menu">
      
     {% if user.is_authenticated %}
      <li class="nav-item"><a id="home" href="/" class="nav-link">Início</a></li>
      <li class="nav-item"><a id="home" href="/home" class="nav-link">Guia</a></li>
      <li class="nav-item"><a id="home" href="/" class="nav-link">Sobre</a></li>
      <div class="logout-button">
        <a href="/logout" class="logout-link">Sair</a>
      </div>
      {% else %}
      <li class="nav-item"><a id="home" href="/" class="nav-link">Início</a></li>
      <li class="nav-item"><a id="signUp" href="/sign-up" class="nav-link">Cadastre-se</a></li>
    <li class="nav-item"><a id="home" href="/" class="nav-link">Sobre</a></li>
      <div class="login-button">
        <a href="/login" class="login-link">Entrar</a>
      </div>
      {% endif %}
  </ul>
  </div>
</header>

<script src="{{ url_for('static', filename='index.js') }}"></script>

    
<!-- Codigo-->

    
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-bs-dismiss="alert"aria-label="Fechar">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-bs-dismiss="alert"aria-label="Fechar">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
      <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    flash: true,
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/home";
  });
  }
</script>
{% endblock %}
    

    
  <footer>
    <div class="interface">
          <a href="/">
    <div class="logo">
        <img src="{{ url_for('static', filename='img/Cinemix.png') }}" alt="Logo Cinemix Movies" class="logo">
    </div>
          </a>
          <!--logo-footer-->
<div class="btn-social">
  <a href="#"><i class="bi bi-facebook"></i></a>
  <a href="#"><i class="bi bi-youtube"></i></a>
  <a href="#"><i class="bi bi-linkedin"></i></a>
</div>
<!-- btn-social -->
        </div>
      <!--line-footer-->

      <div class="line-footer borda">
        <a href="">contato@equipe_cineastas.com.br</a>
      </div>
      <!--line-footer-->
    <!--interface-->
  </footer>
  <!--footer-->    

  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Guia de Recomendação{% endblock %} {% block content
%}

<!--Sistemda de recomendação -->
  
<!-- Formulário de Seleção-->

<div class="form-container">
  <h2> Formulário de Recomendação </h2>
  <form method="POST" action="{{ url_for('views.index') }}">
    <div class="column">
    <label for="genres">Gêneros</label>
    <select id="genres" name="genres" multiple>
      <option value="Action">Action</option>
      <option value="Adventure">Adventure</option>
      <option value="Comedy">Comedy</option>
      <option value="Drama">Drama</option>
      <option value="Science_Fiction">Science Fiction</option>
      <option value="Horror">Horror</option>
      <option value="Romance">Romance</option>
      <option value="Animation">Animation</option>
      <option value="Documentary">Documentary</option>
      <option value="Fantasy">Fantasy</option>
      <option value="Thriller">Thriller</option>

      <!-- Adicione mais opções de gênero aqui -->
    </select>
  </div>
  
  <!--Comentário-->
  
  <div class="column">
    <label for="year">Ano do Filme</label>
    <select id="year" name="year" multiple>
      <option value="2001">2001</option>
      <option value="2002">2002</option>
      <option value="2003">2003</option>
      <option value="2004">2004</option>
      <option value="2005">2005</option>
      <option value="2006">2006</option>
      <option value="2007">2007</option>
      <option value="2008">2008</option>
      <option value="2009">2009</option>
      <option value="2010">2010</option>
      <option value="2011">2011</option>
      <option value="2012">2012</option>
      <option value="2013">2013</option>
      <option value="2014">2014</option>
      <option value="2015">2015</option>
      <option value="2016">2016</option>
      <option value="2017">2017</option>
      <option value="2018">2018</option>
      <option value="2019">2019</option>
      <option value="2020">2020</option>
      <option value="2021">2021</option>
      <option value="2022">2022</option>
      <option value="2023">2023</option>
    </select>
  </div>
  
  
  <div class="column">
    <label for="ratings">Avaliação</label>
    <select id="ratings" name="ratings" multiple>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
      <!-- Adicione mais opções de classificação aqui -->
    </select>
  </div>
      <button type="submit">Gerar Recomendações</button>
  </form>
</div>


<!--Script para exibir os valores selecionados -->
<div class="results">
    <h3>Dados selecionados:</h3>
    <p>Gêneros:{% for genero in generos %}
            {{ genero }}
            {% if not loop.last %}, {% endif %}
        {% endfor %}</p>
    <p>Ano do Filme: {{ ano_lancamento }}</p>
    <p>Avaliação: {{ nota_minima }}</p>
</div>

<!-- Filmes Recomendados -->
{% if recommended_movie_names %}
  <h2 style="text-align: center;">Filmes Recomendados</h2>
  <ul class="gallery">
    {% for i in range(10) %}
      <li class="movie-item">
        <img class="movie-poster" src="{{ recommended_movie_posters[i] }}" alt="Movie Poster">
        <div class="movie-title">{{ recommended_movie_names[i] }}</div>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <h2 style="text-align: center;">Nenhum Filme Recomendado</h2>
  <p style="color:#ffff;">Não encontramos recomendações com base no seu interesse. Por favor, faça outra seleção.</p>

{% endif %}



<!-- Container separado para a seção "Adicionar Notas" -->

<!-- Container separado para a seção "Adicionar Notas" -->
{% if user.is_authenticated %}
  <div class="add-notes-container">
    <!-- Seção: Adicionar Notas -->
    <section class="add-notes-section">
      <h2 align="center">Adicionar Notas</h2>

      <!-- Note Manager -->
      <div class="note-manager">
        <ul class="list-group list-group-flush" id="notes">
          {% for note in user.notes %}
            <li class="list-group-item">
              {{ note.data }}
              <button type="button" class="close" onClick="deleteNote({{ note.id }})">
                <span aria-hidden="true">&times;</span>
              </button>
            </li>
          {% endfor %}
        </ul>

        <!-- Formulário para adicionar notas -->
        <form method="POST" action="{{ url_for('views.home') }}">
          <textarea name="note" id="note" class="form-control"></textarea>
          <br />
          <div align="center">
            <button type="submit" class="btn btn-primary">Salvar Notas</button>
          </div>
        </form>
      </div>
    </section>
  </div>
{% endif %}

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Entrar{% endblock %} {% block content
%}

<div class="login_body">

    <div class="login_box">
      <h2>Fazer Login</h2>
      
<form method="POST">
  <div class="form-group">
    <label for="email">Seu E-mail</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Digite seu e-mail"
    />
  </div>
  <div class="form-group">
    <label for="password">Senha</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Digite sua senha"
    />
  </div>
  <br />
   <input type="hidden" name="next" value="{{ request.args.get('next') }}">
            <button type="submit" class="submit">Entrar</button>
</form>
      <div class="support">
        <div class="remember">
          <span><input type="checkbox" style="margin: 0;padding: 0; height: 13px;"></span>
          <span>Lembre-se de mim</span>
        </div>
        <div class="help">
          <a href="">
            Precisa de ajuda?
          </a>
        </div>
      </div>

  </div>
</div>
  
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Cadastre-se{% endblock %} {% block
content %}

<div class="login_body">

  <div class="login_box">
    <h2>Criar sua conta</h2>

<form method="POST">
  <div class="form-group">
    <label for="email">E-mail</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Seu e-mail"
    />
  </div>
  <div class="form-group">
    <label for="firstName">Nome</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Digite seu nome"
    />
  </div>
  <div class="form-group">
    <label for="password1">Senha</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Digite sua senha"
    />
  </div>
  <div class="form-group">
    <label for="password2">Confirmar Senha</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirmar senha"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Finalizar cadastro</button>
</form>
  </div>
</div>
{% endblock %}